# c.f. https://circleci.com/docs/2.0/language-javascript/
version: 2.1

executors:
  grumpy-executor:
    docker:
      - image: grumpycorp/warm-and-fuzzy-ci:11
    working_directory: ~/camera-slider

jobs:
  build:
    executor: grumpy-executor
    steps:
      # Check out source
      - checkout
      - run: git submodule update --init --recursive

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}

      # Install dependencies
      - run: npm install

      # Save cache
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Run builds
      - run:
          name: Build
          command: |
            if [ "$CIRCLE_BRANCH" == "master" ]; then
              REACT_APP_API_STAGE=prod npm run build -ws
            else
            npm run build -ws
            fi
          environment:
            # Limit NodeJS heap size so we don't OOM
            NODE_OPTIONS: --max_old_space_size=1500

#
# Workflows
#

workflows:
  all:
    jobs:
      - build:
          context: camera-slider-particle
